
@host = localhost:5000

### Suche alle Mails
DELETE http://{{host}}/mail

### Suche mit vorhandener Mail-ID
DELETE http://{{host}}/mail/5f7192a238ca9c4610648754

### Suche mit vorhandener Mail-ID und Versionsnummer
DELETE http://{{host}}/mail/000000000000000000000001
If-None-Match: "0"

### Suche mit vorhandener Mail-ID und falscher Versionsnummer
DELETE http://{{host}}/mail/000000000000000000000001
If-None-Match: 0

### Suche mit ungueltiger Mail-ID
DELETE http://{{host}}/mail/YYYYYYYYYYYYYYYYYYYYYYYY

### Suche mit nicht-vorhandener Mail-ID
DELETE http://{{host}}/mail/000000000000000000000004

### Suche mit gueltiger Mailart
DELETE http://{{host}}/mail?subscribed=true

### Optionen zu Mail-ID
OPTIONS http://{{host}}/mail/00000000-0000-0000-0000-000000000001
