@host = localhost:5000

### Neue Mail anlegen
POST http://{{host}}/mail
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

< .\json\mail\post.json

### Neue Mail mit ungueltigen Daten anlegen
POST http://{{host}}/mail
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

< .\json\mail\post-invalid.json

### Neue Mail ohne Login anlegen
POST http://{{host}}/mail
Content-Type: application/json

< .\json\mail\post.json
