
@host = localhost:5000

### Suche alle member
http://{{host}}/member

### Suche mit vorhandener Member-ID
http://{{host}}/member/000000000000000000000001

### Suche mit vorhandener Member-ID und Versionsnummer
http://{{host}}/member/000000000000000000000001
If-None-Match: "0"

### Suche mit vorhandener Member-ID und falscher Versionsnummer
http://{{host}}/member/000000000000000000000001
If-None-Match: 0

### Suche mit ungueltiger Member-ID
http://{{host}}/member/YYYYYYYYYYYYYYYYYYYYYYYY

### Suche mit nicht-vorhandener Member-ID
http://{{host}}/member/000000000000000000000004

### Suche mit gueltiger Memberart
http://{{host}}/member?subscribed=true

### Optionen zu Member-ID
OPTIONS http://{{host}}/member/00000000-0000-0000-0000-000000000001
