@host = localhost:5000

### Neuer Member anlegen
POST http://{{host}}/member
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

< .\json\member\post.json

### Neuer Member mit ungueltigen Daten anlegen
POST http://{{host}}/member
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

< .\json\member\post-invalid.json

### Neuer Member ohne Login anlegen
POST http://{{host}}/member
Content-Type: application/json

< .\json\member\post.json
