@host = localhost:5000

### Delete mit vorhandener Member-ID
DELETE http://{{host}}/member/000000000000000000000001

### Delete mit nicht-vorhandener Member-ID
DELETE http://{{host}}/member/000000000000000000000004
